language: cpp
os:
  - linux
compiler:
  - gcc
branches:
  only:
  - master
env:
  global:
    - COMPILER=g++-7

script:
  - cd $TRAVIS_BUILD_DIR/LinuxTimer_Test
  - make 
  - ls 
  - ./LinuxTimer_Test
  - cd $TRAVIS_BUILD_DIR
  - sonar-scanner -X
  
addons:
  sonarcloud:
    organization: "freeeyes-github"
    token:
      secure: "ampLEJkUXI49u1ZT+EwuoLrodPq8+CqKznYJswq3WUDiG6QT1eK825dqEFy9Vq1TObiT4eK5vw0hZ/VUKQluifWxBq4QzyBhPM801dV5dyOY1gEgI4jKNAOFnqKpZLlOGJpmof9pp9xD6CxxfA1opZu2BKwkGygugVNach2IwN1v4QLcVes79/kKaOXzcKOzorEz+xwz1x1l3INladdiB33eudYbN1Lz7P6YXrt3Se9ljK63/KadpJRym5XrSj7Yrf8gN/2ZHOz4Oq+qFUHRBwbNXARyzHCI30PvJ2wKqd5fZeCrCOVP/wOGT7CB9aYHsrEGhcclnNKFRDeIuElBuHutnhUQQoaE7ZzG/mc4D6g6KIUktmQVaw/N35tlbJ6PLjpINrHH38nPo9YKKv56v+sSwBPBXVojN/LddQ8TjtOvP2J8AJ0SLyhVckbT7mCgQMmGsOmC9YyiztAbSvAvOi+4G4bggvRV+rptoekW/Nkc6i8WosAJ8V0kvt9Kpcz6miao+5VbTMpRupyNI44lvFXuoF/LE2C14aIN2aW4taYFpzm7wanIzyLDgGJZNeGOT2kPL9zdsu35qGKDGhmA46RqNZPrmj0+3KXIfnzw3EDGEGOYBXQvtaxF2YP98HUMulgodyVxIDtGA2BivEvcgSD68lKks2+T/BXIbNwpMf0="
        
