language: cpp
os:
  - linux
compiler:
  - gcc
branches:
  only:
  - master
env:
  global:
    - COMPILER=g++-7

script:
  - cd $TRAVIS_BUILD_DIR/LinuxTimer_Test
  - make 
  - ls 
  - ./LinuxTimer_Test
  - cd ../
  - sonar-scanner -X
  
addons:
  sonarcloud:
    organization: "freeeyes-github"
    token:
      secure: "qzWDGQvGlJlBvJyG+jhAQXRU3K6n0tf+u6goSNMnW9K1/qkJLThO158V8o4N/Yu4JE5L7hIVlSUUuJbU6xEWWazm4x4rI4KGQ8z8K6F7Jm7kshpNybp8PzibkOiB7K2F8+adrk9bELeYGSA06UqlAtvSn5Q22GlFq+Zwlp8RYGFcZHNOaK0GGPPRu4xHdDMIBhpg5kwjEEpYbfWYmhJJRqNzkityhBxylvcCCnln6FDUpgRbIdCzntl2f5Ctp8ZA9zS5ZX/XMOIbtEePT8DisBQ6s0wMIjthBgEhI9om8yphNe8QYv8Y9kfcK+dvpOvm9RKXZrmzXBKgl2JEmp9vxYFLspQy0y4oVeM7l+7gPa6Bj3lpszbOhZZtHmoBQh7RETW5Fmg3ubKDi9+vGWx417k/JRjdGD8NHHDPDhcDSWCgx85y2UcpO1JUY1LoLl7pF6HAQkFG+Eb3wO7bogvgTd46QJixrmJu/kCC7bFVhKVGGpgRq1A4h4dkwfDvTw8w5zL74zd7AdghwfqihEq2PwfizADCoaszocgOg4kmqIsakuVaGE7r4fo4E4sShcb036OIQz2F6gJmLMgasTMG5E1s+K/j2m3QOZ2fLIyKm2/0rKbL9jYvtYf27FWpBKyPnyIKNegZSu7F/RDEGk2qMkIeK7iuV/4DsDXgJcXMiHk="
        
