language: cpp
os:
  - linux
compiler:
  - gcc
branches:
  only:
  - master
env:
  global:
    - COMPILER=g++-7

script:
  - cd $TRAVIS_BUILD_DIR/LinuxTimer_Test
  - build-wrapper-linux-x86-64 --out-dir bw-output make -j 4
  - make 
  - ls 
  - ./LinuxTimer_Test
  - cd $TRAVIS_BUILD_DIR
  - sonar-scanner -X
  
addons:
  sonarcloud:
    organization: "freeeyes-github"
    token:
      secure: "IvjaJWPjCb9CWXzwYZhI4y35Q+4fz+AdJF+W/rfpqcBdNu0SD3MBEpcWt5jaiTYEU5CuMjIxpPmRtA607TB/CKGGluBVzUHny0Ua8jRM1WvjQE4Z7JwLdsFwEhrjFTDLOmvXntSUM3HLh9pEiyoyvYL4ZGNfzNemtAyBXgCqUkzn7RcuadJRT76/9O26QB58P1gy6faFAZqTsK31hM7burDAi32H/NLlEoQCfftSjwPtNwKjxv7iJav/x77yCVl5QKbNGQJTp0dT/nwsWV/3bf8L3YRkdnJ1x+DIsN+uN8LJlJMCyO75tf0EL+t1kLtNMifW0fLTBdOW1c30awbQ31G1qvCiEitGxffkT2wMC3DUmolT10wh9N4ZoyAte2APjHcav/Y36yMAfFgSnA4eWIkHCi0Fn3ljoXyuYJRPRa2iVRdUTbOqpRTuy25jWN5HjsnBCtDrfe2SRo36DMTJCAlWR+yJePWs6hsARvz19Dx/Hbm75pZFOG4ZPYysAOFTC/W4PgAjSX8kp/kSvd8GpjL+b5AIxDJ0c7JHesBYDqJBDKNj8fONF3+HWssB7Ofsrcz5F7w49TfUod920M6TzWDCAJMK9L0rGL9CAoDSbNOqAD2zG3FppiSE8iBHcTpw3+Q+aCENyws1CNKQFBmyg0hMk9OM9GysmjRn2mkgrj8="
        
