language: cpp
os:
  - linux
compiler:
  - gcc
branches:
  only:
  - master
env:
  global:
    - COMPILER=g++-7

script:
  - cd $TRAVIS_BUILD_DIR/LinuxTimer_Test
  - make 
  - ls 
  - ./LinuxTimer_Test
  - cd ../
  - sonar-scanner -X
  
addons:
  sonarcloud:
    organization: "freeeyes-github"
    token:
      secure: "wIjOa9g9Cb4XEIfLz6ydcpEUpkkd12WQkU3YhRSTcjqN6py/oog0JvgWl6LKkGIwkCdLh4DIdpV1LhZfUx3FnjB6z2ZKRBTEsQWRckOpAT5XzomyeMmG35bm9hJVG6uv9AzFszqDiIEr0V02dnWEwUEDDVUryfqRs+ejGMVBKD2szzCw0LeiDQ/dlXhLVy5CHQi0hWUc5esPf7UeIT68Q7v+GfuF2KvkImllTjmEmhs2JMRUASEqcxL2kmecivSm0ZMjc3QtfDTkqLz+DKOmMWJfhAE1DPHR9/rJimlJUdCiZoxVbaDR9MkREa1DL8BHV3RhrVQh0Ze5TcWXyIvvkM8jCyejNkNCyJa5GMH1F0osQvqr0UaK6Y55Jvb/Nu+MlTPb/3xKcEXbcitBmJR5EIaKl2wu7uuPmje9E+7Wlq2Q2W3kaQpiY+HhpRtb5pubWwxcpPbcww+WSMHFzrdkpq5pMllrmrAolygxJyS1hyWrIPxnIPF+L17UyTViKWUyADOakTNVPkpIxuuwFUZAkzR5zmDZD0qZdt1VgXePDXX+zOKfBEJcvRFgh46KbIwvEPsS6rqDIvimBRAjcupuYPFF0CK0M8ZJVw2hWE3H7li7DfzX9xgeBFNABKspAMPdYC2GgeU+9LiHXfmzDRGSOUut2arZ8ZDdGIQitgyZyYw="
        
